# Generated by Django 3.2.7 on 2021-09-14 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('goal', models.FloatField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('description', models.CharField(max_length=5000, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=42)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('addressTo', models.CharField(max_length=42)),
                ('completed', models.BooleanField(default=False)),
                ('numberOfVoters', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='fundraising.project')),
            ],
        ),
    ]
