# Generated by Django 3.2.7 on 2021-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0004_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='numberOfVoters',
            field=models.IntegerField(default=0),
        ),
    ]
