# Generated by Django 3.2.7 on 2021-09-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0005_alter_request_numberofvoters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='fundraising.project'),
        ),
    ]
