# Generated by Django 3.2.7 on 2021-09-21 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraising', '0006_alter_request_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favourite',
            field=models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
