# Generated by Django 3.2.7 on 2021-09-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0007_project_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favourite',
        ),
    ]
