# Generated by Django 3.2.7 on 2021-09-22 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fundraising', '0008_remove_project_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='added_to_favourite',
            field=models.ManyToManyField(blank=True, related_name='projects', to='accounts.Profile'),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraising.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
