# Generated by Django 3.2.7 on 2021-09-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0009_auto_20210922_0312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
