# Generated by Django 3.2.7 on 2021-09-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0010_delete_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='added_to_favourite',
        ),
    ]
